name: CI/CD Pipeline for Go Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  IMAGE_NAME: "109.172.89.231:5000/registry"
  CONTAINER_NAME: "crud-server-container"
  REGISTRY: "109.172.89.231:5000"

jobs:
  image-build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker to use insecure registry
        run: |
          echo '{ "insecure-registries":["109.172.89.231:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use 
          docker buildx build --no-cache --platform linux/amd64 -t  $REGISTRY:$TAG_NAME .